# Generated by Django 5.0.6 on 2024-06-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='name',
        ),
    ]
