# Generated by Django 5.0.6 on 2024-06-05 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_remove_postmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='body',
            field=models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created DateTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='name',
            field=models.CharField(db_index=True, default='Anonimous', max_length=14, verbose_name='Name'),
        ),
        migrations.AlterModelTable(
            name='postmodel',
            table='post',
        ),
    ]
