# Generated by Django 5.0.6 on 2024-06-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_postmodel_body_postmodel_created_at_postmodel_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postmodel',
            new_name='Post',
        ),
    ]
