# Generated by Django 5.0.6 on 2024-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0004_rename_postmodel_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, default='Anonimous', max_length=30, verbose_name='Name'),
        ),
    ]
